# GitHub CI test pipeline
name: CI testing battleships game code

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Unit Tests
      run: |
        python battleships_test.py